## N维数组 - ndarray

### ndarray的属性
1. ndarray.shape: 数组维度的元组
2. ndarray.ndim: 数组维数
3. ndarray.size: 数组中的元素数量
4. ndarray.itemsize: 一个数组元素的长度(字节)
5. ndarray.dtype: 数组元素的类型

In [51]:
import numpy as np

score = np.array([[12, 13, 14, 15, 16], [23, 24, 25, 26, 27], [34, 35, 36, 37, 38], [45, 46, 47, 48, 49], [51, 52, 53, 54, 55]])

score

array([[12, 13, 14, 15, 16],
       [23, 24, 25, 26, 27],
       [34, 35, 36, 37, 38],
       [45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55]])

In [52]:
score.shape

(5, 5)

In [53]:
score.ndim  # 有两层，二维数组

2

In [54]:
score.size  # 一共25个数据

25

In [55]:
score.itemsize  # 每个数据的字节长度为8

8

In [56]:
score.dtype

dtype('int64')

### ndarray的形状
1. np.array()
    - 三维数组不好理解 -- excel中有多个sheet

In [57]:
a = np.array([10, 20, 30])

a

array([10, 20, 30])

In [58]:
b = np.array([[10, 20, 30], [20, 30, 40]])

b

array([[10, 20, 30],
       [20, 30, 40]])

In [59]:
c = np.array([[[10, 20, 30], [20, 30, 40]], [[30, 40, 50], [50, 60, 70]]])

c

array([[[10, 20, 30],
        [20, 30, 40]],

       [[30, 40, 50],
        [50, 60, 70]]])

In [60]:
a.shape

(3,)

In [61]:
b.shape  # 两大块，每块里面3个

(2, 3)

In [62]:
c.shape  # 两大块，每块里面两个，每个里面3个

(2, 2, 3)

### ndarray的类型
1. 有很多
2. 若不指定，整数默认int64，小数默认float64

In [63]:
a.dtype

dtype('int64')

In [64]:
# 指定类型
d = np.array([10, 20, 30], dtype=np.float32)

d.dtype

dtype('float32')

In [65]:
e = np.array(["I", "love", "u"], dtype=np.string_)

In [66]:
e

array([b'I', b'love', b'u'], dtype='|S4')